# Generated by Django 6.0.2 on 2026-03-09 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hotels', '0002_remove_hotel_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='applied_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_bookings_with_offer', to='hotels.offer'),
        ),
    ]
