# Generated by Django 6.0.2 on 2026-02-27 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_type', models.CharField(choices=[('5_STAR', '5 Star Premium'), ('4_STAR', '4 Star Luxury'), ('3_STAR', '3 Star Business'), ('RESORT', 'Resort / Villa'), ('OTHER', 'Other Property'), ('HOTEL', 'Hotel'), ('VILLA', 'Villa'), ('GUESTHOUSE', 'Guest House'), ('HOSTEL', 'Hostel')], max_length=20)),
                ('services', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('total_rooms', models.PositiveIntegerField(blank=True, default=0, help_text='Total unit count of the property')),
                ('check_in', models.CharField(default='14:00', max_length=10)),
                ('check_out', models.CharField(default='11:00', max_length=10)),
                ('cancellation_policy', models.TextField(default='Standard Rules Apply')),
                ('id_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN Card')], default='AADHAAR', max_length=10)),
                ('id_number', models.CharField(blank=True, help_text='Aadhaar or PAN Number', max_length=20, null=True)),
                ('doc_mandatory', models.FileField(blank=True, help_text='Primary ID File', null=True, upload_to='compliance/identity/')),
                ('govt_reg_number', models.CharField(blank=True, help_text='Government Registration Number', max_length=50, null=True)),
                ('doc_certificate', models.FileField(blank=True, help_text='Govt Certificate File', null=True, upload_to='compliance/certificate/')),
                ('gst_number', models.CharField(blank=True, help_text='GST Identification Number', max_length=15, null=True)),
                ('doc_gst', models.FileField(blank=True, help_text='GST Certificate File', null=True, upload_to='compliance/gst/')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('LIVE', 'Live & Active'), ('REJECTED', 'Rejected / Action Required')], default='PENDING', max_length=15)),
                ('verification_remarks', models.TextField(blank=True, help_text='Feedback from Super Admin', null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IDENTITY', 'Property Identity'), ('INVENTORY', 'Room Inventory'), ('GALLERY', 'Photo Gallery'), ('OPS', 'Policies & Ops')], max_length=20)),
                ('requested_data', models.JSONField(help_text='The proposed new data')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Admin feedback', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='property_gallery/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Offer Title')),
                ('offer_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FLAT', 'Flat Discount'), ('SEASONAL', 'Seasonal Offer'), ('EARLY_BIRD', 'Early Bird Offer'), ('LAST_MINUTE', 'Last Minute Deal'), ('WEEKEND', 'Weekend Offer'), ('COUPON', 'Coupon Code Offer'), ('MIN_STAY', 'Minimum Stay Offer'), ('BULK', 'Bulk Booking Discount')], default='PERCENTAGE', max_length=20)),
                ('discount_type', models.CharField(choices=[('PERCENT', '%'), ('FIXED', '₹')], default='PERCENT', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Max ₹ discount possible', max_digits=10, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('applicability', models.CharField(choices=[('ALL', 'Entire Hotel'), ('CATEGORY', 'Selected Room Categories'), ('ROOM', 'Specific Rooms')], default='ALL', max_length=20)),
                ('room_categories', models.JSONField(blank=True, default=list, help_text='IDs of room types this applies to.')),
                ('specific_rooms', models.JSONField(blank=True, default=list, help_text='Specific room identifiers if applicable.')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('blackout_dates', models.JSONField(blank=True, default=list, help_text='List of specific dates (ISO format) where offer is NOT valid.')),
                ('applicable_days', models.JSONField(blank=True, default=list, help_text='List of days (0-6) where this offer is valid.')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min Booking Amount')),
                ('min_nights', models.PositiveIntegerField(default=1, verbose_name='Min Nights Stay')),
                ('max_nights', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Nights Stay')),
                ('advance_booking_days', models.PositiveIntegerField(default=0, help_text='Days in advance to book')),
                ('last_minute_window', models.PositiveIntegerField(default=0, help_text='Book within X days of check-in')),
                ('max_usage', models.PositiveIntegerField(default=0, help_text='0 for unlimited')),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('is_stackable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=15)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_category_name', models.CharField(blank=True, help_text='e.g. Deluxe Garden View', max_length=100, null=True)),
                ('room_type', models.CharField(choices=[('STANDARD', 'Standard Room'), ('DELUXE', 'Deluxe Room'), ('SUITE', 'Suite'), ('LUXURY', 'Luxury / Presidential Room'), ('DORM', 'Dormitory Bed'), ('PRIVATE', 'Private Room')], max_length=20)),
                ('price_per_night', models.PositiveIntegerField(default=0)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('total_rooms', models.PositiveIntegerField(help_text='Inventory count for this specific type')),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='room_categories/')),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
    ]
