# Generated by Django 6.0.2 on 2026-03-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='room_size',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_in',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out',
            field=models.TimeField(default='11:00'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(choices=[('5_STAR', '5 Star Premium'), ('4_STAR', '4 Star Luxury'), ('3_STAR', '3 Star Business'), ('RESORT', 'Resort / Villa'), ('HOTEL', 'Hotel'), ('BOUTIQUE', 'Boutique Hotel'), ('BUSINESS', 'Business Hotel'), ('BUDGET', 'Budget Hotel'), ('LUXURY', 'Luxury Hotel'), ('HERITAGE', 'Heritage Hotel'), ('AIRPORT', 'Airport Hotel'), ('BEACH_RESORT', 'Beach Resort'), ('HILL_RESORT', 'Hill Resort'), ('SERVICED_APT', 'Serviced Apartments'), ('VACATION_RENTAL', 'Vacation Rentals'), ('HOMESTAY', 'Homestay'), ('GUESTHOUSE', 'Guest House'), ('HOSTEL', 'Hostel'), ('LODGE', 'Lodge'), ('MOTEL', 'Motel'), ('VILLA', 'Villa'), ('ECO_RESORT', 'Eco Resort'), ('WELLNESS', 'Wellness Retreat'), ('PALACE', 'Palace Hotel'), ('CASINO', 'Casino Resort'), ('SPA_RESORT', 'Spa Resort'), ('GOLF_RESORT', 'Golf Resort'), ('SKI_RESORT', 'Ski Resort'), ('DESERT_CAMP', 'Desert Camp'), ('HOUSEBOAT', 'Houseboat'), ('FARM_STAY', 'Farm Stay'), ('OTHER', 'Other Property')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Room'), ('DELUXE', 'Deluxe Room'), ('SUITE', 'Suite'), ('LUXURY', 'Luxury / Presidential Room'), ('ECONOMY', 'Economy Room'), ('PREMIUM', 'Premium Room'), ('EXECUTIVE', 'Executive Room'), ('CLUB', 'Club Room'), ('PRESIDENTIAL', 'Presidential Suite'), ('ROYAL', 'Royal Suite'), ('FAMILY', 'Family Room'), ('SPECIALTY', 'Specialty Room'), ('DORM', 'Dormitory Bed'), ('PRIVATE', 'Private Room'), ('CUSTOM', 'Custom Category')], max_length=20),
        ),
    ]
