# Generated by Django 6.0.2 on 2026-03-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_roomcategory_hotelgallery_roomphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='hotels.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel'),
        ),
    ]
