# Generated by Django 6.0.2 on 2026-03-10 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_roomcategory_hotel_alter_offer_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomphoto',
            name='room_category',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='room_category_name',
        ),
        migrations.AddField(
            model_name='roomphoto',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotels.roomtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='name',
            field=models.CharField(default='Room', help_text='Example: Deluxe Garden View', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='hotels.hotel'),
        ),
        migrations.DeleteModel(
            name='RoomCategory',
        ),
    ]
