# Generated by Django 6.0.2 on 2026-03-10 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_roomphoto_room_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelimage',
            options={'verbose_name': 'Hotel Image', 'verbose_name_plural': 'Hotel Images'},
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_in',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.DeleteModel(
            name='HotelGallery',
        ),
    ]
