# Generated by Django 6.0.2 on 2026-03-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotelimage_options_alter_hotel_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
    ]
