# Generated by Django 6.0.2 on 2026-03-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotel_onboarding_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='combinable_offers',
            field=models.ManyToManyField(blank=True, to='hotels.offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='targeted_hotels',
            field=models.ManyToManyField(blank=True, related_name='targeted_offers', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='offer',
            name='targeted_rooms',
            field=models.ManyToManyField(blank=True, related_name='targeted_offers', to='hotels.roomtype'),
        ),
    ]
