# Generated by Django 6.0 on 2026-04-01 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_offer_combinable_offers_offer_targeted_hotels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='room_image',
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.ImageField(upload_to='room_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='hotels.roomtype')),
            ],
            options={
                'verbose_name': 'Room Photo',
                'verbose_name_plural': 'Room Photos',
            },
        ),
    ]
