# Generated by Django 6.0 on 2026-04-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_remove_roomtype_room_image_roomimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomPhoto',
        ),
    ]
