# Generated by Django 6.0.2 on 2026-03-03 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('total_guests', models.SmallIntegerField()),
                ('adults', models.SmallIntegerField()),
                ('children', models.SmallIntegerField()),
                ('payment_method', models.CharField(default='cash', max_length=20)),
                ('booking_status', models.CharField(default='confirm', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_hotel_bookings', to='hotels.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_room_bookings', to='hotels.roomtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
