# Generated by Django 6.0.2 on 2026-03-09 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('hotels', '0002_remove_hotel_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='applied_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.offer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
