# Generated by Django 6.0.2 on 2026-03-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_applied_offer_booking_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
    ]
